### ISSUE TITLE
Unable to decode

### ISSUE THREAD

**Issue by ghost** [h4wkst3r/InvisibilityCloak#11]
Traceback (most recent call last):
  File "C:\Users\main\Downloads\InvisibilityCloak.py", line 542, in <module>
    main(theObfMethod, theDirectory, theName)
  File "C:\Users\main\Downloads\InvisibilityCloak.py", line 497, in main
    replaceGUIDAndToolName(theDirectory, theName)
  File "C:\Users\main\Downloads\InvisibilityCloak.py", line 150, in replaceGUIDAndToolName
    for line in openAssemblyInfoFile.readlines():
  File "C:\Users\main\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 85: character maps to <undefined>

**Comment by h4wkst3r** [comment]
Can you please provide more details about how you are executing the tool and against which project(s)?

**Comment by ghost** [comment]
python InvisibilityCloak.py -d "C:\Users\main\source\repos\ToxicEye" -n "test" -m base64

https://github.com/LimerBoy/ToxicEye/tree/master

If it cannot be fixed its okay, for I no longer have the time to work on this (school)

**Comment by h4wkst3r** [comment]
There is currently not support for obfuscating this project. Closing issue.

**Comment by AryaAnish121** [comment]
I got the same error and after debugging I found out that the project contained Chinese characters in the comments. Maybe you could look into that
