### ISSUE TITLE
Testing with Rubeus

### ISSUE THREAD

**Issue by init5-SF** [h4wkst3r/InvisibilityCloak#2]
Hey, thanks for the great tool!
I've been testing it against Rubeus, but even after cloaking, Defender still flags it.

With rot13 method, this is the result:
```
[!] Identified end of bad bytes at offset 0x4903B
00000000   72 65 73 73 00 44 6F 6D  61 69 6E 43 6F 6E 74 72   ress·DomainContr
00000010   6F 6C 6C 65 72 41 64 64  72 65 73 73 00 48 6F 73   ollerAddress·Hos
00000020   74 41 64 64 72 65 73 73  00 61 64 64 72 65 73 73   tAddress·address
00000030   00 63 72 6F 73 73 00 75  73 65 72 53 74 61 74 73   ·cross·userStats
00000040   00 45 6E 75 6D 65 72 61  74 65 54 69 63 6B 65 74   ·EnumerateTicket
00000050   73 00 50 61 72 73 65 53  61 76 65 54 69 63 6B 65   s·ParseSaveTicke
00000060   74 73 00 73 61 76 65 54  69 63 6B 65 74 73 00 43   ts·saveTickets·C
00000070   6F 75 6E 74 4F 66 54 69  63 6B 65 74 73 00 48 61   ountOfTickets·Ha
00000080   72 76 65 73 74 54 69 63  6B 65 74 47 72 61 6E 74   rvestTicketGrant
00000090   69 6E 67 54 69 63 6B 65  74 73 00 77 72 61 70 54   ingTickets·wrapT
000000A0   69 63 6B 65 74 73 00 64  69 73 70 6C 61 79 4E 65   ickets·displayNe
000000B0   77 54 69 63 6B 65 74 73  00 72 65 6E 65 77 54 69   wTickets·renewTi
000000C0   63 6B 65 74 73 00 67 65  74 5F 61 64 64 69 74 69   ckets·get_additi
000000D0   6F 6E 61 6C 5F 74 69 63  6B 65 74 73 00 73 65 74   onal_tickets·set
000000E0   5F 61 64 64 69 74 69 6F  6E 61 6C 5F 74 69 63 6B   _additional_tick
000000F0   65 74 73 00 67 65 74 5F  74 69 63 6B 65 74 73 00   ets·get_tickets·
```

With the base64 method, it still gets flagged, but it breaks ThreatCheck so I can't see the bad bytes

```
[+] Target file size: 315392 bytes
[+] Analyzing...

Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Temp\file.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at ThreatCheck.Defender.AnalyzeFile()
   at ThreatCheck.Program.RunOptions(Options opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ThreatCheck.Program.Main(String[] args)
```

Do you have any suggestions? :-)

**Comment by h4wkst3r** [comment]
Hey there! Yes, Rubeus is one of the tools that has some signatures in method/variable names, which are things that InvisibilityCloak doesn't obfuscate yet. However, what you can do to get around this is run Rubeus through ConfuserEx (linked below) after compiling the InvisibilityCloak version. 

https://github.com/yck1509/ConfuserEx/releases

**Comment by init5-SF** [comment]
Thanks! Will do.
